package com.lathaeps.lathabulk;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ContentResolver;
import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.provider.OpenableColumns;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.PopupMenu;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.core.content.FileProvider;

import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class QuotationActivity extends Activity {
    private static final String PREFS="lathaeps_quotation_manager";
    private static final String ITEMS="quote_items", SOURCES="quote_sources";
    private static final int PICK_SOURCE_IMAGES=701, PICK_SOURCE_FILES=702, CAPTURE_MATERIAL_LIST=703;
    private SharedPreferences prefs;
    private LinearLayout itemCards;
    private TextView quoteSummary, customerSummary;
    private Runnable sourceRefresh;
    private File capturedMaterialFile;

    @Override protected void onCreate(Bundle state){
        super.onCreate(state);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);setContentView(buildScreen());
    }

    private View buildScreen(){
        LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setFitsSystemWindows(true);page.setPadding(dp(10),dp(10),dp(10),dp(10));page.setBackgroundColor(Color.rgb(246,244,249));
        LinearLayout header=row();header.setGravity(Gravity.CENTER_VERTICAL);header.setBackground(rounded(Color.rgb(91,41,145),18));
        Button back=button("‹");back.setTextSize(31);back.setTextColor(Color.WHITE);back.setBackgroundColor(Color.TRANSPARENT);TextView title=text("Business Quotation",23,Color.WHITE,true);header.addView(back,new LinearLayout.LayoutParams(dp(50),dp(58)));header.addView(title,new LinearLayout.LayoutParams(0,dp(58),1f));page.addView(header);back.setOnClickListener(v->finish());

        LinearLayout tools=row();Button sources=button("SOURCE /\nMATERIAL LISTS");Button letterhead=button("EDIT COMPANY\nHEADER");for(Button b:new Button[]{sources,letterhead}){b.setTextSize(11);b.setMaxLines(2);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(Color.rgb(91,41,145));}tools.addView(sources,weighted(1.15f,54));tools.addView(letterhead,weighted(1f,54));page.addView(tools);sources.setOnClickListener(v->showSourceManager());letterhead.setOnClickListener(v->showLetterheadSettings());

        Button camera=button("CAMERA • AI READ MATERIAL LIST");camera.setTypeface(Typeface.DEFAULT_BOLD);camera.setTextColor(Color.WHITE);camera.setBackground(rounded(Color.rgb(0,125,93),14));LinearLayout.LayoutParams cameraLp=new LinearLayout.LayoutParams(-1,dp(48));cameraLp.setMargins(dp(2),dp(3),dp(2),dp(5));page.addView(camera,cameraLp);camera.setOnClickListener(v->captureMaterialList());

        customerSummary=text("",14,Color.DKGRAY,false);customerSummary.setPadding(dp(12),dp(8),dp(12),dp(8));customerSummary.setBackground(rounded(Color.WHITE,14));page.addView(customerSummary,new LinearLayout.LayoutParams(-1,dp(62)));customerSummary.setOnClickListener(v->showCustomerDetails());

        LinearLayout quoteTools=row();Button add=button("+ ADD MATERIAL ITEM");Button discounts=button("DISCOUNT STRUCTURE");add.setTypeface(Typeface.DEFAULT_BOLD);add.setTextColor(Color.rgb(0,110,70));discounts.setTypeface(Typeface.DEFAULT_BOLD);discounts.setTextColor(Color.rgb(170,95,0));quoteTools.addView(add,weighted(1.2f,48));quoteTools.addView(discounts,weighted(1f,48));page.addView(quoteTools);add.setOnClickListener(v->showAddItemOptions());discounts.setOnClickListener(v->showDiscountSettings());

        quoteSummary=text("",13,Color.DKGRAY,true);quoteSummary.setPadding(dp(7),dp(4),dp(7),dp(4));quoteSummary.setMaxLines(2);page.addView(quoteSummary,new LinearLayout.LayoutParams(-1,dp(54)));
        ScrollView scroll=new ScrollView(this);itemCards=new LinearLayout(this);itemCards.setOrientation(LinearLayout.VERTICAL);itemCards.setPadding(0,dp(3),0,dp(10));scroll.addView(itemCards);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));

        LinearLayout outputs=row();outputs.setPadding(0,dp(4),0,dp(4));Button preview=button("PREVIEW");Button image=button("SHARE\nIMAGE");Button pdf=button("SHARE\nPDF");for(Button b:new Button[]{preview,image,pdf}){b.setTextSize(11);b.setMaxLines(2);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(Color.WHITE);}preview.setBackground(rounded(Color.rgb(91,41,145),14));image.setBackground(rounded(Color.rgb(23,112,155),14));pdf.setBackground(rounded(Color.rgb(190,45,45),14));outputs.addView(preview,weighted(.8f,58));outputs.addView(image,weighted(1f,58));outputs.addView(pdf,weighted(1f,58));page.addView(outputs,new LinearLayout.LayoutParams(-1,dp(66)));preview.setOnClickListener(v->showPreview());image.setOnClickListener(v->shareQuoteImage());pdf.setOnClickListener(v->shareQuotePdf());
        refreshAll();return page;
    }

    private void refreshAll(){renderItems();String no=prefs.getString("quote_no","").trim(),customer=prefs.getString("customer_name","").trim(),details=prefs.getString("customer_details","").trim();String prefix=no.isEmpty()?"":"QUOTE "+no+" • ";customerSummary.setText(customer.isEmpty()&&details.isEmpty()&&no.isEmpty()?"CUSTOMER (OPTIONAL) • Tap to add name & details":prefix+"CUSTOMER • "+(customer.isEmpty()?"Name optional":customer)+(details.isEmpty()?"":"\n"+details));}

    private JSONArray readArray(String key){try{return new JSONArray(prefs.getString(key,"[]"));}catch(Exception e){return new JSONArray();}}
    private void writeArray(String key,JSONArray value){prefs.edit().putString(key,value.toString()).apply();}

    private void renderItems(){
        itemCards.removeAllViews();JSONArray items=readArray(ITEMS);Totals totals=calculateTotals(items);for(int i=0;i<items.length();i++){JSONObject o=items.optJSONObject(i);if(o==null)continue;final int index=i;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(9),dp(10),dp(8));card.setBackground(rounded(Color.WHITE,15));LinearLayout top=row();TextView name=text((i+1)+". "+o.optString("name","Material"),17,Color.rgb(61,35,90),true);Button more=button("⋮");more.setTextSize(23);more.setBackgroundColor(Color.TRANSPARENT);top.addView(name,new LinearLayout.LayoutParams(0,dp(40),1f));top.addView(more,new LinearLayout.LayoutParams(dp(44),dp(40)));card.addView(top);String detail=o.optString("details","");double qty=num(o,"qty"),rate=num(o,"rate"),disc=num(o,"discount"),gst=num(o,"gst"),base=qty*rate,discAmount=base*disc/100.0,taxable=base-discAmount,gstAmount=taxable*gst/100.0;TextView meta=text((detail.isEmpty()?"":detail+"\n")+fmt(qty)+" "+o.optString("unit","Nos")+" × ₹"+money(rate)+" = ₹"+money(base)+"\nDisc "+fmt(disc)+"% (-₹"+money(discAmount)+") • GST "+fmt(gst)+"% (+₹"+money(gstAmount)+")\nItem Total ₹"+money(lineTotal(o)),14,Color.DKGRAY,false);card.addView(meta);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(7));itemCards.addView(card,lp);card.setOnClickListener(v->showItemEditor(o,index));more.setOnClickListener(v->showItemMenu(more,o,index));}
        if(items.length()==0){TextView empty=text("No material items added\nTap + ADD MATERIAL ITEM",17,Color.GRAY,false);empty.setGravity(Gravity.CENTER);itemCards.addView(empty,new LinearLayout.LayoutParams(-1,dp(170)));}
        quoteSummary.setText(items.length()+" items • Subtotal ₹"+money(totals.subtotal)+" • Discount ₹"+money(totals.itemDiscount+totals.overallDiscount)+"\nGST ₹"+money(totals.gst)+" • GRAND TOTAL ₹"+money(totals.grand));
    }

    private void showItemMenu(View anchor,JSONObject item,int index){PopupMenu menu=new PopupMenu(this,anchor);menu.getMenu().add("Edit item");menu.getMenu().add("Duplicate item");menu.getMenu().add("Delete item");menu.setOnMenuItemClickListener(x->{String action=x.getTitle().toString();if(action.startsWith("Edit"))showItemEditor(item,index);else if(action.startsWith("Duplicate"))duplicateItem(item);else confirmDeleteItem(index,item.optString("name","item"));return true;});menu.show();}
    private void showAddItemOptions(){JSONArray savedPrices;try{savedPrices=new JSONArray(getSharedPreferences(MainActivity.PREFS,MODE_PRIVATE).getString(MainActivity.PRICE_LIST_ITEMS_KEY,"[]"));}catch(Exception e){savedPrices=new JSONArray();}if(savedPrices.length()==0){showItemEditor(null,-1);return;}final JSONArray prices=savedPrices;String[] choices=new String[prices.length()+1];choices[0]="+ New manual material item";for(int i=0;i<prices.length();i++){JSONObject o=prices.optJSONObject(i);choices[i+1]=(o==null?"Price item":o.optString("brand","")+" • "+o.optString("name","Item")+" • ₹"+o.optString("rate","0"));}new AlertDialog.Builder(this).setTitle("Add Material Item").setItems(choices,(d,w)->{if(w==0){showItemEditor(null,-1);return;}JSONObject source=prices.optJSONObject(w-1);if(source==null){showItemEditor(null,-1);return;}try{JSONObject item=new JSONObject();item.put("id",System.currentTimeMillis());item.put("name",source.optString("name","Material"));item.put("details",source.optString("brand","")+((source.optString("category","").isEmpty())?"":" • "+source.optString("category")));item.put("qty",1);item.put("unit",source.optString("unit","Nos"));item.put("rate",source.optDouble("rate",parse(source.optString("rate","0"),0)));item.put("discount",source.optDouble("discount",parse(source.optString("discount","0"),0)));item.put("gst",source.optDouble("gst",parse(source.optString("gst",String.valueOf(defaultGst())),defaultGst())));showItemEditor(item,-1);}catch(Exception e){showItemEditor(null,-1);}}).setNegativeButton("CANCEL",null).show();}
    private void duplicateItem(JSONObject item){try{JSONArray a=readArray(ITEMS);a.put(new JSONObject(item.toString()).put("id",System.currentTimeMillis()));writeArray(ITEMS,a);renderItems();toast("Item duplicated");}catch(Exception e){toast("Duplicate failed");}}
    private void confirmDeleteItem(int index,String name){new AlertDialog.Builder(this).setTitle("Delete "+name+"?").setPositiveButton("DELETE",(d,w)->{JSONArray a=readArray(ITEMS),out=new JSONArray();for(int i=0;i<a.length();i++)if(i!=index)out.put(a.opt(i));writeArray(ITEMS,out);renderItems();}).setNegativeButton("CANCEL",null).show();}

    private void showItemEditor(JSONObject old,int index){
        LinearLayout box=form();EditText name=input("Material / Item name *"),details=input("Item details / model (optional)"),qty=input("Quantity"),unit=input("Unit • Nos, Mtr, Box"),rate=input("Rate ₹"),disc=input("Discount %"),gst=input("GST %");qty.setInputType(2|8192);rate.setInputType(2|8192);disc.setInputType(2|8192);gst.setInputType(2|8192);if(old!=null){name.setText(old.optString("name"));details.setText(old.optString("details"));qty.setText(fmt(num(old,"qty")));unit.setText(old.optString("unit","Nos"));rate.setText(fmt(num(old,"rate")));disc.setText(fmt(num(old,"discount")));gst.setText(fmt(num(old,"gst")));}else{qty.setText("1");unit.setText("Nos");disc.setText(fmt(defaultDiscount()));gst.setText(fmt(defaultGst()));}for(EditText e:new EditText[]{name,details,qty,unit,rate,disc,gst})box.addView(e);
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle(old==null?"Add Separate Material Item":"Edit Material Item").setView(box).setPositiveButton("SAVE",null).setNegativeButton("CANCEL",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{String n=name.getText().toString().trim();if(n.isEmpty()){name.setError("Item name required");return;}double q=parse(qty.getText().toString(),1),r=parse(rate.getText().toString(),0),d=parse(disc.getText().toString(),0),g=parse(gst.getText().toString(),0);if(q<=0){qty.setError("Quantity must be above 0");return;}try{JSONObject saved=new JSONObject();saved.put("id",old==null?System.currentTimeMillis():old.optLong("id",System.currentTimeMillis()));saved.put("name",n);saved.put("details",details.getText().toString().trim());saved.put("qty",q);saved.put("unit",unit.getText().toString().trim().isEmpty()?"Nos":unit.getText().toString().trim());saved.put("rate",r);saved.put("discount",Math.max(0,Math.min(100,d)));saved.put("gst",Math.max(0,g));JSONArray a=readArray(ITEMS),out=new JSONArray();for(int i=0;i<a.length();i++)out.put(i==index?saved:a.opt(i));if(index<0)out.put(saved);writeArray(ITEMS,out);dialog.dismiss();renderItems();}catch(Exception e){toast("Item save failed");}}));dialog.show();
    }

    private void showCustomerDetails(){LinearLayout box=form();EditText quoteNo=input("Quotation number / reference (optional)"),subject=input("Subject / project details (optional)"),name=input("Customer name (optional)"),details=input("Address / phone / GST / details (optional)");details.setMinLines(3);quoteNo.setText(prefs.getString("quote_no",""));subject.setText(prefs.getString("quote_subject",""));name.setText(prefs.getString("customer_name",""));details.setText(prefs.getString("customer_details",""));box.addView(quoteNo);box.addView(subject);box.addView(name);box.addView(details);new AlertDialog.Builder(this).setTitle("Quotation & Customer Details").setMessage("Customer name aur saari details optional hain.").setView(box).setPositiveButton("SAVE",(d,w)->{prefs.edit().putString("quote_no",quoteNo.getText().toString().trim()).putString("quote_subject",subject.getText().toString().trim()).putString("customer_name",name.getText().toString().trim()).putString("customer_details",details.getText().toString().trim()).apply();refreshAll();}).setNeutralButton("CLEAR",(d,w)->{prefs.edit().remove("quote_no").remove("quote_subject").remove("customer_name").remove("customer_details").apply();refreshAll();}).setNegativeButton("CANCEL",null).show();}

    private void showDiscountSettings(){LinearLayout box=form();EditText discount=input("Default item discount %"),gst=input("Default GST %"),overall=input("Additional overall quotation discount %");for(EditText e:new EditText[]{discount,gst,overall})e.setInputType(2|8192);discount.setText(fmt(defaultDiscount()));gst.setText(fmt(defaultGst()));overall.setText(fmt(overallDiscount()));box.addView(discount);box.addView(gst);box.addView(overall);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Discount & Total Structure").setMessage("Item discount har material par alag ho sakta hai. Overall discount item discounts ke baad poori quotation par lagega; subtotal, discount, GST aur grand total automatic calculate honge.").setView(box).setPositiveButton("SAVE",null).setNeutralButton("APPLY ITEM % TO ALL",null).setNegativeButton("CANCEL",null).create();dialog.setOnShowListener(v->{View.OnClickListener save=x->{double d=percent(discount.getText().toString()),g=Math.max(0,parse(gst.getText().toString(),0)),o=percent(overall.getText().toString());prefs.edit().putString("default_discount",String.valueOf(d)).putString("default_gst",String.valueOf(g)).putString("overall_discount",String.valueOf(o)).apply();renderItems();toast("Discount and total settings saved");dialog.dismiss();};dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(save);dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(x->{double d=percent(discount.getText().toString()),g=Math.max(0,parse(gst.getText().toString(),0)),o=percent(overall.getText().toString());JSONArray a=readArray(ITEMS);try{for(int i=0;i<a.length();i++){JSONObject item=a.optJSONObject(i);if(item!=null){item.put("discount",d);item.put("gst",g);}}writeArray(ITEMS,a);prefs.edit().putString("default_discount",String.valueOf(d)).putString("default_gst",String.valueOf(g)).putString("overall_discount",String.valueOf(o)).apply();renderItems();toast("Discount and GST applied to all items");dialog.dismiss();}catch(Exception e){toast("Update failed");}});});dialog.show();}
    private double defaultDiscount(){return parse(prefs.getString("default_discount","0"),0);}private double defaultGst(){return parse(prefs.getString("default_gst","18"),18);}private double overallDiscount(){return percent(prefs.getString("overall_discount","0"));}

    private void showLetterheadSettings(){LinearLayout box=form();EditText business=input("Company name shown in quotation header"),address=input("Address"),contact=input("Phone / email"),gst=input("GST number"),terms=input("Quotation terms / validity");address.setMinLines(2);terms.setMinLines(2);business.setText(prefs.getString("lh_business","LATHA ENTERPRISES"));address.setText(prefs.getString("lh_address","No. 40 & 41, Shop No. 15, Arihant Darshan Complex, Annapillai Street, Sowcarpet, Chennai - 600001"));contact.setText(prefs.getString("lh_contact","9025156444 • 044-45116270 • lathaeps@gmail.com"));gst.setText(prefs.getString("lh_gst","33AFBPV5535K1Z7"));terms.setText(prefs.getString("lh_terms","Rates are subject to confirmation. Quotation valid for 7 days."));for(EditText e:new EditText[]{business,address,contact,gst,terms})box.addView(e);new AlertDialog.Builder(this).setTitle("Edit Company Header / Letter Pad").setMessage("Company name yahan edit karke har quotation header me use hoga.").setView(box).setPositiveButton("SAVE",(d,w)->{String company=business.getText().toString().trim();if(company.isEmpty())company="LATHA ENTERPRISES";prefs.edit().putString("lh_business",company).putString("lh_address",address.getText().toString().trim()).putString("lh_contact",contact.getText().toString().trim()).putString("lh_gst",gst.getText().toString().trim()).putString("lh_terms",terms.getText().toString().trim()).apply();toast("Company header saved");}).setNegativeButton("CANCEL",null).show();}

    private void showSourceManager(){
        LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(12),dp(8),dp(12),dp(12));Button camera=button("CAMERA + AI READ");camera.setTextColor(Color.rgb(0,115,78));page.addView(camera,new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout picks=row();Button gallery=button("+ GALLERY IMAGES");Button files=button("+ PDF / FILES");picks.addView(gallery,weighted(1f,48));picks.addView(files,weighted(1f,48));page.addView(picks);TextView note=text("Camera se material list scan karke AI text read karega. Detected items ko review/edit karke quotation me import karein. Gallery/PDF source files bhi alag save rehte hain.",13,Color.DKGRAY,false);note.setPadding(dp(5),dp(7),dp(5),dp(7));page.addView(note);ScrollView scroll=new ScrollView(this);LinearLayout cards=new LinearLayout(this);cards.setOrientation(LinearLayout.VERTICAL);scroll.addView(cards);page.addView(scroll,new LinearLayout.LayoutParams(-1,dp(390)));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Quotation Source Files").setView(page).setPositiveButton("DONE",null).create();sourceRefresh=()->renderSources(cards);camera.setOnClickListener(v->captureMaterialList());gallery.setOnClickListener(v->pickSourceImages());files.setOnClickListener(v->pickSourceFiles());dialog.setOnDismissListener(v->sourceRefresh=null);sourceRefresh.run();dialog.show();
    }

    private void renderSources(LinearLayout cards){cards.removeAllViews();JSONArray a=readArray(SOURCES);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;final int index=i;LinearLayout card=row();card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(12),dp(7),dp(6),dp(7));card.setBackground(rounded(Color.rgb(244,239,249),12));String type=o.optString("type","").contains("pdf")?"PDF":"IMAGE";TextView name=text(o.optString("name","Source file")+"\n"+type,14,Color.rgb(61,35,90),true);Button open=button("OPEN");Button more=button("⋮");more.setTextSize(22);card.addView(name,new LinearLayout.LayoutParams(0,dp(58),1f));card.addView(open,new LinearLayout.LayoutParams(dp(70),dp(44)));card.addView(more,new LinearLayout.LayoutParams(dp(42),dp(44)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(66));lp.setMargins(0,0,0,dp(6));cards.addView(card,lp);open.setOnClickListener(v->openSource(o));more.setOnClickListener(v->showSourceMenu(more,o,index));}if(a.length()==0){TextView empty=text("No source PDF / image saved",16,Color.GRAY,false);empty.setGravity(Gravity.CENTER);cards.addView(empty,new LinearLayout.LayoutParams(-1,dp(130)));}}
    private void showSourceMenu(View anchor,JSONObject source,int index){PopupMenu menu=new PopupMenu(this,anchor);if(source.optString("type","").startsWith("image/"))menu.getMenu().add("AI read material list");menu.getMenu().add("Share file");menu.getMenu().add("Rename file");menu.getMenu().add("Delete file");menu.setOnMenuItemClickListener(x->{String a=x.getTitle().toString();if(a.startsWith("AI read"))recognizeMaterialList(new File(source.optString("path")));else if(a.startsWith("Share"))shareSource(source);else if(a.startsWith("Rename"))renameSource(index,source);else deleteSource(index,source);return true;});menu.show();}
    private void renameSource(int index,JSONObject source){EditText name=input("Source name");name.setText(source.optString("name"));name.setSelectAllOnFocus(true);new AlertDialog.Builder(this).setTitle("Rename Source").setView(name).setPositiveButton("SAVE",(d,w)->{try{JSONArray a=readArray(SOURCES);JSONObject o=a.optJSONObject(index);if(o!=null)o.put("name",name.getText().toString().trim());writeArray(SOURCES,a);if(sourceRefresh!=null)sourceRefresh.run();}catch(Exception e){toast("Rename failed");}}).setNegativeButton("CANCEL",null).show();}
    private void deleteSource(int index,JSONObject source){new AlertDialog.Builder(this).setTitle("Delete source file?").setMessage(source.optString("name")).setPositiveButton("DELETE",(d,w)->{JSONArray a=readArray(SOURCES),out=new JSONArray();for(int i=0;i<a.length();i++)if(i!=index)out.put(a.opt(i));writeArray(SOURCES,out);String path=source.optString("path","");if(!path.isEmpty())new File(path).delete();if(sourceRefresh!=null)sourceRefresh.run();}).setNegativeButton("CANCEL",null).show();}
    private void openSource(JSONObject source){try{Uri uri=fileUri(source);Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(uri,source.optString("type","application/octet-stream"));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Open quotation source"));}catch(Exception e){toast("File open failed");}}
    private void shareSource(JSONObject source){try{Uri uri=fileUri(source);Intent i=new Intent(Intent.ACTION_SEND);i.setType(source.optString("type","application/octet-stream"));i.putExtra(Intent.EXTRA_STREAM,uri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share quotation source"));}catch(Exception e){toast("Share failed");}}
    private Uri fileUri(JSONObject source){return FileProvider.getUriForFile(this,getPackageName()+".fileprovider",new File(source.optString("path")));}

    private void pickSourceImages(){Intent i=new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(Intent.createChooser(i,"Select material/price list images"),PICK_SOURCE_IMAGES);}
    private void pickSourceFiles(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/pdf","image/jpeg","image/png","image/webp"});i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(Intent.createChooser(i,"Select source PDF / images"),PICK_SOURCE_FILES);}
    private void captureMaterialList(){try{File dir=new File(getFilesDir(),"business_files/quotation_sources");if(!dir.exists()&&!dir.mkdirs())throw new Exception("Folder unavailable");capturedMaterialFile=new File(dir,"camera_material_"+System.currentTimeMillis()+".jpg");Uri uri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",capturedMaterialFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,uri);i.setClipData(ClipData.newRawUri("material_list",uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(i,CAPTURE_MATERIAL_LIST);}catch(Exception e){toast("Camera open failed");}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==CAPTURE_MATERIAL_LIST){boolean photoReady=capturedMaterialFile!=null&&capturedMaterialFile.exists()&&capturedMaterialFile.length()>0;if(photoReady){saveCapturedSource(capturedMaterialFile);if(sourceRefresh!=null)sourceRefresh.run();recognizeMaterialList(capturedMaterialFile);}else if(capturedMaterialFile!=null)capturedMaterialFile.delete();return;}if(resultCode!=RESULT_OK||data==null||(requestCode!=PICK_SOURCE_IMAGES&&requestCode!=PICK_SOURCE_FILES))return;LinkedHashMap<String,Uri> selected=new LinkedHashMap<>();ClipData clips=data.getClipData();if(clips!=null)for(int i=0;i<clips.getItemCount();i++){Uri u=clips.getItemAt(i).getUri();if(u!=null)selected.put(u.toString(),u);}if(data.getData()!=null)selected.put(data.getData().toString(),data.getData());int saved=0;for(Uri uri:selected.values())if(saveSource(uri))saved++;if(sourceRefresh!=null)sourceRefresh.run();toast(saved+" source files saved");}
    private void saveCapturedSource(File file){try{JSONArray a=readArray(SOURCES);JSONObject saved=new JSONObject();saved.put("id",System.currentTimeMillis()+"_camera");saved.put("name","Camera Material List "+new SimpleDateFormat("dd-MM-yyyy HH:mm",Locale.getDefault()).format(new Date()));saved.put("type","image/jpeg");saved.put("path",file.getAbsolutePath());saved.put("updated",System.currentTimeMillis());a.put(saved);writeArray(SOURCES,a);}catch(Exception e){toast("Camera source save failed");}}
    private boolean saveSource(Uri uri){File out=null;try{String name=displayName(uri),mime=getContentResolver().getType(uri);if(mime==null)mime=name.toLowerCase(Locale.ROOT).endsWith(".pdf")?"application/pdf":"image/jpeg";String ext=mime.contains("pdf")?"pdf":mime.contains("png")?"png":mime.contains("webp")?"webp":"jpg";File dir=new File(getFilesDir(),"business_files/quotation_sources");if(!dir.exists()&&!dir.mkdirs())throw new Exception("Folder unavailable");out=new File(dir,"source_"+System.currentTimeMillis()+"_"+Math.abs(uri.toString().hashCode())+"."+ext);try(InputStream in=getContentResolver().openInputStream(uri);OutputStream stream=new FileOutputStream(out)){if(in==null)throw new Exception("Read failed");byte[] b=new byte[16384];int n;while((n=in.read(b))>0)stream.write(b,0,n);}JSONArray a=readArray(SOURCES);JSONObject saved=new JSONObject();saved.put("id",System.currentTimeMillis()+"_"+a.length());saved.put("name",name);saved.put("type",mime);saved.put("path",out.getAbsolutePath());saved.put("updated",System.currentTimeMillis());a.put(saved);writeArray(SOURCES,a);return true;}catch(Exception e){if(out!=null)out.delete();return false;}}
    private String displayName(Uri uri){String name="Source_"+System.currentTimeMillis();try(Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst()){String n=c.getString(0);if(n!=null&&!n.trim().isEmpty())name=n;}}catch(Exception ignored){}return name;}

    private void recognizeMaterialList(File file){
        if(file==null||!file.exists()){toast("Material list image not found");return;}
        toast("AI material list read ho rahi hai…");
        final TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);
        try{
            Uri uri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",file);
            InputImage image=InputImage.fromFilePath(this,uri);
            recognizer.process(image)
                    .addOnSuccessListener(result->{recognizer.close();String raw=result.getText()==null?"":result.getText().trim();if(raw.isEmpty()){new AlertDialog.Builder(this).setTitle("Text clear nahi mila").setMessage("Photo ko seedha, achhi light aur clear focus me lekar dobara try karein.").setPositiveButton("RETRY CAMERA",(d,w)->captureMaterialList()).setNegativeButton("CLOSE",null).show();return;}showOcrReview(raw);})
                    .addOnFailureListener(error->{recognizer.close();new AlertDialog.Builder(this).setTitle("Camera AI read failed").setMessage("Photo save ho gayi hai, lekin text read nahi hua. Clear focus aur seedhi photo se retry karein, ya items manually add karein.").setPositiveButton("RETRY CAMERA",(d,w)->captureMaterialList()).setNegativeButton("CLOSE",null).show();});
        }catch(Exception e){recognizer.close();toast("Image read failed");}
    }

    private void showOcrReview(String raw){
        String prepared=prepareDetectedItems(raw);
        EditText review=input("Item | Qty | Unit | Rate | Disc% | GST%");review.setSingleLine(false);review.setMinLines(11);review.setGravity(Gravity.TOP);review.setText(prepared.isEmpty()?raw:prepared);review.setSelection(review.getText().length());
        ScrollView scroll=new ScrollView(this);scroll.addView(review,new ScrollView.LayoutParams(-1,-2));
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Business Assistant • AI Read").setMessage("Har line: Item | Qty | Unit | Rate | Disc% | GST%\nImport ke baad Qty × Rate, discount, GST aur grand total automatic calculate hoga.").setView(scroll).setPositiveButton("IMPORT & CALCULATE",null).setNeutralButton("CLEAR",null).setNegativeButton("CANCEL",null).create();
        dialog.setOnShowListener(v->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{int added=importDetectedItems(review.getText().toString());if(added<=0){review.setError("Kam se kam ek material line rakhein");return;}dialog.dismiss();renderItems();toast(added+" AI-read items quotation me added");});dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(x->review.setText(""));});dialog.show();
    }

    private String prepareDetectedItems(String raw){
        StringBuilder out=new StringBuilder();String[] lines=raw.replace('\r','\n').split("\\n+");
        Pattern number=Pattern.compile("(?<![A-Za-z])\\d+(?:[.,]\\d+)?(?![A-Za-z])");
        Pattern unitPattern=Pattern.compile("(?i)\\b(nos?|pcs?|pieces?|mtrs?|meters?|metres?|box(?:es)?|rolls?|sets?|kg|pairs?|pkt|packets?)\\b");
        Pattern qtyUnitPattern=Pattern.compile("(?i)(\\d+(?:[.,]\\d+)?)\\s*(nos?|pcs?|pieces?|mtrs?|meters?|metres?|box(?:es)?|rolls?|sets?|kg|pairs?|pkt|packets?)\\b");
        Pattern discPattern=Pattern.compile("(?i)(?:disc(?:ount)?|less)\\s*[:=\\-]?\\s*(\\d+(?:[.,]\\d+)?)\\s*%?");
        Pattern gstPattern=Pattern.compile("(?i)(?:gst|tax)\\s*[:=\\-]?\\s*(\\d+(?:[.,]\\d+)?)\\s*%?");
        int count=0;
        for(String source:lines){if(count>=100)break;String line=source.replace('|',' ').replaceAll("\\s+"," ").trim();if(line.length()<2)continue;String lower=line.toLowerCase(Locale.ROOT);if(lower.matches(".*\\b(subtotal|grand total|quotation|estimate|material list|description|particulars|amount|invoice|customer|address|phone|gstin)\\b.*")&&lower.length()<80)continue;line=line.replaceFirst("^\\s*\\d{1,3}[.)-]\\s*","");
            double disc=defaultDiscount(),gst=defaultGst();Matcher dm=discPattern.matcher(line),gm=gstPattern.matcher(line);if(dm.find())disc=percent(dm.group(1));if(gm.find())gst=Math.max(0,parseCleanNumber(gm.group(1),gst));
            String working=discPattern.matcher(gstPattern.matcher(line).replaceAll(" ")).replaceAll(" ").replaceAll("\\d+(?:[.,]\\d+)?\\s*%"," ").replaceAll("\\s+"," ").trim();
            double qty=1,rate=0;String unit="Nos",itemName="";Matcher qu=qtyUnitPattern.matcher(working);
            if(qu.find()){qty=Math.max(0.0001,parseCleanNumber(qu.group(1),1));unit=normalUnit(qu.group(2));itemName=working.substring(0,qu.start()).replaceAll("[-:=]+$","").trim();String tail=working.substring(qu.end());Matcher tailNumbers=number.matcher(tail);if(tailNumbers.find())rate=Math.max(0,parseCleanNumber(tailNumbers.group(),0));}
            else{Matcher m=number.matcher(working);List<Integer> starts=new ArrayList<>();List<Double> nums=new ArrayList<>();while(m.find()){starts.add(m.start());nums.add(parseCleanNumber(m.group(),0));}if(nums.isEmpty()){if(!working.matches(".*[A-Za-z].*"))continue;itemName=working;}else{qty=Math.max(0.0001,nums.get(0));if(nums.size()>1)rate=Math.max(0,nums.get(1));itemName=working.substring(0,starts.get(0)).replaceAll("[-:=]+$","").trim();}}
            itemName=unitPattern.matcher(itemName).replaceAll(" ").replaceAll("(?i)(?:₹|Rs\\.?|INR)"," ").replaceAll("\\s+"," ").trim();if(itemName.length()<2)continue;
            if(out.length()>0)out.append('\n');out.append(itemName).append(" | ").append(fmt(qty)).append(" | ").append(unit).append(" | ").append(fmt(rate)).append(" | ").append(fmt(disc)).append(" | ").append(fmt(gst));count++;
        }
        return out.toString();
    }

    private int importDetectedItems(String reviewed){
        JSONArray items=readArray(ITEMS);int added=0;String[] lines=reviewed.replace('\r','\n').split("\\n+");
        for(String source:lines){String line=source.trim();if(line.isEmpty())continue;String[] parts=line.split("\\|",-1);String name=parts[0].trim();if(name.isEmpty())continue;double qty=parts.length>1?parseCleanNumber(parts[1],1):1;String unit=parts.length>2?normalUnit(parts[2].trim()):"Nos";double rate=parts.length>3?parseCleanNumber(parts[3],0):0,disc=parts.length>4?percent(parts[4]):defaultDiscount(),gst=parts.length>5?Math.max(0,parseCleanNumber(parts[5],defaultGst())):defaultGst();if(qty<=0)qty=1;if(unit.isEmpty())unit="Nos";try{JSONObject item=new JSONObject();item.put("id",System.currentTimeMillis()+added);item.put("name",name);item.put("details","AI camera scan • Please verify");item.put("qty",qty);item.put("unit",unit);item.put("rate",Math.max(0,rate));item.put("discount",disc);item.put("gst",gst);items.put(item);added++;}catch(Exception ignored){}}
        if(added>0)writeArray(ITEMS,items);return added;
    }

    private void showPreview(){if(readArray(ITEMS).length()==0){toast("Pehle material items add karein");return;}Bitmap bitmap=createQuoteBitmap();ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setImageBitmap(bitmap);ScrollView scroll=new ScrollView(this);scroll.addView(image);new AlertDialog.Builder(this).setTitle("Letter Pad Preview").setView(scroll).setPositiveButton("PDF",(d,w)->shareQuotePdf()).setNeutralButton("IMAGE",(d,w)->shareQuoteImage()).setNegativeButton("CLOSE",null).show();}
    private void shareQuoteImage(){if(readArray(ITEMS).length()==0){toast("Pehle material items add karein");return;}try{File dir=quoteOutputDir();File out=new File(dir,fileBase()+".png");try(FileOutputStream stream=new FileOutputStream(out)){createQuoteBitmap().compress(Bitmap.CompressFormat.PNG,100,stream);}shareOutput(out,"image/png","Share quotation image");}catch(Exception e){toast("Quotation image failed");}}
    private void shareQuotePdf(){if(readArray(ITEMS).length()==0){toast("Pehle material items add karein");return;}PdfDocument pdf=new PdfDocument();Bitmap bitmap=createQuoteBitmap();try{int pageW=595,pageH=842,sourcePage=Math.max(1,(int)Math.floor(bitmap.getWidth()*(pageH-36.0)/(pageW-36.0)));int pages=(int)Math.ceil(bitmap.getHeight()/(double)sourcePage);Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);for(int pageNo=0;pageNo<pages;pageNo++){PdfDocument.Page page=pdf.startPage(new PdfDocument.PageInfo.Builder(pageW,pageH,pageNo+1).create());int top=pageNo*sourcePage,bottom=Math.min(bitmap.getHeight(),top+sourcePage);Rect src=new Rect(0,top,bitmap.getWidth(),bottom),dst=new Rect(18,18,pageW-18,18+(int)((bottom-top)*(pageW-36.0)/bitmap.getWidth()));page.getCanvas().drawColor(Color.WHITE);page.getCanvas().drawBitmap(bitmap,src,dst,paint);pdf.finishPage(page);}File out=new File(quoteOutputDir(),fileBase()+".pdf");try(FileOutputStream stream=new FileOutputStream(out)){pdf.writeTo(stream);}shareOutput(out,"application/pdf","Share quotation PDF");}catch(Exception e){toast("Quotation PDF failed");}finally{pdf.close();bitmap.recycle();}}
    private void shareOutput(File file,String mime,String title){Uri uri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",file);Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime);i.putExtra(Intent.EXTRA_STREAM,uri);i.putExtra(Intent.EXTRA_TEXT,"Quotation from "+prefs.getString("lh_business","LATHA ENTERPRISES"));i.setClipData(ClipData.newRawUri("quotation",uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,title));}
    private File quoteOutputDir()throws Exception{File dir=new File(getFilesDir(),"business_files/quotations");if(!dir.exists()&&!dir.mkdirs())throw new Exception("Folder unavailable");return dir;}
    private String fileBase(){String no=prefs.getString("quote_no","").trim();if(no.isEmpty())no=new SimpleDateFormat("yyyyMMdd_HHmm",Locale.getDefault()).format(new Date());return "LATHA_EPS_Quotation_"+no.replaceAll("[^A-Za-z0-9_-]","_");}

    private Bitmap createQuoteBitmap(){JSONArray items=readArray(ITEMS);int width=1240,height=Math.max(1754,980+items.length()*130);Bitmap bitmap=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(bitmap);c.drawColor(Color.WHITE);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));p.setColor(Color.rgb(91,41,145));c.drawRect(0,0,width,235,p);p.setColor(Color.WHITE);p.setTextSize(54);c.drawText(prefs.getString("lh_business","LATHA ENTERPRISES"),55,78,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(25);int y=120;y=drawWrapped(c,p,prefs.getString("lh_address","No. 40 & 41, Shop No. 15, Arihant Darshan Complex, Annapillai Street, Sowcarpet, Chennai - 600001"),55,y,1120,31);c.drawText(prefs.getString("lh_contact","9025156444 • 044-45116270 • lathaeps@gmail.com"),55,y+5,p);p.setTextSize(22);c.drawText("GST: "+prefs.getString("lh_gst","33AFBPV5535K1Z7"),55,y+40,p);
        y=285;p.setColor(Color.rgb(91,41,145));p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(43);c.drawText("QUOTATION",55,y,p);p.setTextSize(23);p.setTypeface(Typeface.DEFAULT);String no=prefs.getString("quote_no","").trim();if(no.isEmpty())no="Auto";c.drawText("Quote No: "+no,820,y-10,p);c.drawText("Date: "+new SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).format(new Date()),820,y+25,p);
        String subject=prefs.getString("quote_subject","").trim(),customer=prefs.getString("customer_name","").trim(),details=prefs.getString("customer_details","").trim();y+=55;if(!subject.isEmpty()){p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(23);p.setColor(Color.rgb(50,50,50));y=drawWrapped(c,p,"Subject: "+subject,55,y,1120,30);y+=10;}if(!customer.isEmpty()||!details.isEmpty()){p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(25);p.setColor(Color.rgb(50,50,50));c.drawText("To: "+(customer.isEmpty()?"Customer":customer),55,y,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(21);if(!details.isEmpty())y=drawWrapped(c,p,details,55,y+34,1120,28);y+=25;}
        p.setColor(Color.rgb(91,41,145));c.drawRect(45,y,1195,y+55,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(20);c.drawText("ITEM / MATERIAL",60,y+36,p);c.drawText("QTY",585,y+36,p);c.drawText("RATE",690,y+36,p);c.drawText("DISC",815,y+36,p);c.drawText("GST",930,y+36,p);c.drawText("AMOUNT",1040,y+36,p);y+=55;Totals totals=calculateTotals(items);for(int i=0;i<items.length();i++){JSONObject o=items.optJSONObject(i);if(o==null)continue;double amount=lineTotal(o);int rowH=o.optString("details","").isEmpty()?78:108;p.setColor(i%2==0?Color.rgb(248,246,251):Color.WHITE);c.drawRect(45,y,1195,y+rowH,p);p.setColor(Color.rgb(35,35,35));p.setTextSize(20);p.setTypeface(Typeface.DEFAULT_BOLD);String name=(i+1)+". "+o.optString("name","Material");if(name.length()>39)name=name.substring(0,36)+"...";c.drawText(name,60,y+31,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(17);String detailsText=o.optString("details","");if(!detailsText.isEmpty()){if(detailsText.length()>55)detailsText=detailsText.substring(0,52)+"...";c.drawText(detailsText,78,y+60,p);}p.setTextSize(19);c.drawText(fmt(num(o,"qty"))+" "+o.optString("unit","Nos"),575,y+36,p);c.drawText("₹"+money(num(o,"rate")),680,y+36,p);c.drawText(fmt(num(o,"discount"))+"%",815,y+36,p);c.drawText(fmt(num(o,"gst"))+"%",930,y+36,p);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("₹"+money(amount),1030,y+36,p);p.setColor(Color.LTGRAY);c.drawLine(45,y+rowH,1195,y+rowH,p);y+=rowH;}
        y+=24;p.setColor(Color.DKGRAY);p.setTypeface(Typeface.DEFAULT);p.setTextSize(22);c.drawText("SUBTOTAL",785,y+25,p);c.drawText("₹"+money(totals.subtotal),1020,y+25,p);c.drawText("ITEM DISCOUNT",785,y+58,p);c.drawText("-₹"+money(totals.itemDiscount),1020,y+58,p);c.drawText("OVERALL DISC "+fmt(overallDiscount())+"%",785,y+91,p);c.drawText("-₹"+money(totals.overallDiscount),1020,y+91,p);c.drawText("GST",785,y+124,p);c.drawText("+₹"+money(totals.gst),1020,y+124,p);p.setColor(Color.rgb(91,41,145));p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(31);c.drawText("GRAND TOTAL",785,y+168,p);c.drawText("₹"+money(totals.grand),1010,y+168,p);y+=230;p.setColor(Color.DKGRAY);p.setTextSize(21);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("Terms:",55,y,p);p.setTypeface(Typeface.DEFAULT);y=drawWrapped(c,p,prefs.getString("lh_terms","Rates are subject to confirmation. Quotation valid for 7 days."),140,y,1040,29);p.setTextSize(18);p.setColor(Color.GRAY);c.drawText("Generated by LATHAEPS SMART",55,height-45,p);return bitmap;}

    private int drawWrapped(Canvas c,Paint p,String value,int x,int y,int maxWidth,int lineHeight){String[] paragraphs=value.replace("\r","").split("\n");for(String paragraph:paragraphs){String line="";for(String word:paragraph.split("\\s+")){String test=line.isEmpty()?word:line+" "+word;if(p.measureText(test)>maxWidth&&!line.isEmpty()){c.drawText(line,x,y,p);y+=lineHeight;line=word;}else line=test;}if(!line.isEmpty()){c.drawText(line,x,y,p);y+=lineHeight;}}return y;}
    private static class Totals{double subtotal,itemDiscount,overallDiscount,gst,grand;}
    private Totals calculateTotals(JSONArray items){Totals t=new Totals();double taxable=0,gstBeforeOverall=0;for(int i=0;i<items.length();i++){JSONObject o=items.optJSONObject(i);if(o==null)continue;double base=Math.max(0,num(o,"qty"))*Math.max(0,num(o,"rate")),disc=base*percent(String.valueOf(num(o,"discount")))/100.0,itemTaxable=base-disc;t.subtotal+=base;t.itemDiscount+=disc;taxable+=itemTaxable;gstBeforeOverall+=itemTaxable*Math.max(0,num(o,"gst"))/100.0;}double overallRate=overallDiscount()/100.0;t.overallDiscount=taxable*overallRate;t.gst=gstBeforeOverall*(1-overallRate);t.grand=Math.max(0,taxable-t.overallDiscount+t.gst);return t;}
    private double lineTotal(JSONObject o){double base=Math.max(0,num(o,"qty"))*Math.max(0,num(o,"rate")),taxable=base*(1-percent(String.valueOf(num(o,"discount")))/100.0);return taxable*(1+Math.max(0,num(o,"gst"))/100.0);}private double num(JSONObject o,String key){return o==null?0:o.optDouble(key,0);}
    private double percent(String value){return Math.max(0,Math.min(100,parseCleanNumber(value,0)));}
    private double parseCleanNumber(String value,double fallback){try{String s=value==null?"":value.trim().replaceAll("(?i)[₹%]|Rs\\.?|INR","").replace(" ","");if(s.contains(",")&&!s.contains(".")){if(s.matches(".*,[0-9]{3}$"))s=s.replace(",","");else s=s.replace(',','.');}else s=s.replace(",","");return Double.parseDouble(s);}catch(Exception e){return fallback;}}
    private String normalUnit(String raw){String u=raw==null?"":raw.trim().toLowerCase(Locale.ROOT);if(u.startsWith("mtr")||u.startsWith("meter")||u.startsWith("metre"))return "Mtr";if(u.startsWith("box"))return "Box";if(u.startsWith("roll"))return "Roll";if(u.startsWith("set"))return "Set";if(u.equals("kg"))return "Kg";if(u.startsWith("pair"))return "Pair";if(u.startsWith("pkt")||u.startsWith("packet"))return "Pkt";return "Nos";}
    private double parse(String s,double fallback){try{return Double.parseDouble(s.trim());}catch(Exception e){return fallback;}}private String fmt(double n){return Math.abs(n-Math.rint(n))<0.00001?String.valueOf((long)Math.rint(n)):String.format(Locale.US,"%.2f",n);}private String money(double n){return String.format(new Locale("en","IN"),"%,.2f",n);}

    private LinearLayout form(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);return box;}private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(!hint.toLowerCase(Locale.ROOT).contains("details")&&!hint.toLowerCase(Locale.ROOT).contains("address")&&!hint.toLowerCase(Locale.ROOT).contains("terms"));return e;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private LinearLayout.LayoutParams weighted(float w,int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(h),w);p.setMargins(dp(2),dp(2),dp(2),dp(2));return p;}private Button button(String label){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(13);return b;}private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);t.setGravity(Gravity.CENTER_VERTICAL);return t;}private GradientDrawable rounded(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
